### ISSUE TITLE
Include the source command

### ISSUE THREAD

**Issue by marcoliceti** [glenpike/npm-g_nosudo#13]
I tried the script 2 times.

The first time I just launched it and ignored the output, so I didn't notice this tip:

```
Don't forget to run 'source ~/.bashrc'
```

If you _do_ forget, then you'll lose commands installed via npm.

Since the purpose is to _automate_ [this procedure](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md), I think that additional step should be included in the script.

**Comment by glenpike** [comment]
It is possible to run that command inside a shell script, but then the variables you are source'ing are only available inside the process that's running, e.g. the script and would not then be available inside your shell.  Hence the reminder.  You don't have to run that command, next time you start a shell session, you would get the variables in your environment (provided it's setup to source your ~/.bashrc from your ~/.profile, or other, depending on the system you have.

Closing this as a "can't fix" as it's not possible to do what you are asking.
