### ISSUE TITLE
No npm-cli command excuted

### ISSUE THREAD

**Issue by m7ammad88nimer** [glenpike/npm-g_nosudo#16]
After wget the sh file, no npm-cli command excuted.
Such as "yo" command shows "yo: command not found"

**Comment by glenpike** [comment]
Try in a new terminal window - you need to source your changed profile / bash_rc so that it can find your new npm / node binaries in the .npm-packages folder.

**Comment by glenpike** [comment]
Can you tell me if the problem still exists, or if it is resolved - whether that was by using a new terminal / sourcing your bashrc file?

Failing that, I'll close this bug in a few days.

**Comment by m7ammad88nimer** [comment]
Its resolved, Thank you, i followed the npm steps to install --global without permissions.
