### ISSUE TITLE
Yo still not found

### ISSUE THREAD

**Issue by Revod** [glenpike/npm-g_nosudo#17]
HI, I download the script with
```bash
wget -O- https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh | sh
```
and all work fine, but when I install yo and try the "yo" in my terminal I get:
```
yo: command not found
```

I Run: npm -g list -depth=0
and get:
```
├── bower@1.6.5
├── generator-webapp@1.1.0
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── gulp@3.9.0
└── yo@1.4.8

```
Using elementary OS (based ubuntu 14.04) 32 bit.

**Comment by glenpike** [comment]
Possible duplicate of #16 please try solution in there and close this bug if resolved.  I will update readme.

**Comment by Revod** [comment]
thanks @glenpike the problem was fixed
