### ISSUE TITLE
Yeoman Doctor problem - NODE_PATH matches the npm root

### ISSUE THREAD

**Issue by ucassh** [glenpike/npm-g_nosudo#20]
After that spell:
```
wget -O- https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh | sh
source ~/.bashrc
```
I get 
```
✔ Global configuration file is valid
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✖ NODE_PATH matches the npm root
npm global root value is not in your NODE_PATH

[Info]
  NODE_PATH = /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
  npm root  = /home/vagrant/.npm-packages/lib/node_modules

[Fix] Append the npm root value to your NODE_PATH variable
Add this line to your .bashrc
    export NODE_PATH=$NODE_PATH:/home/vagrant/.npm-packages/lib/node_modules
  Or run this command
    echo "export NODE_PATH=$NODE_PATH:/home/vagrant/.npm-packages/lib/node_modules" >> ~/.bashrc && source ~/.bashrc

```
when I'm running yeoman install via 
```
npm install -g grunt-cli bower yo generator-karma generator-angular
```

When I'm doing nosudo manually (via https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md), everything is ok.
```
$ node -v; npm -v
v4.2.2
3.4.0
```

**Comment by glenpike** [comment]
When you ran the script, I am assuming you asked it to modify your bashrc file from the commands you pasted.

The script is _supposed_ to add the NODE_PATH to this file (see [Line 116](https://github.com/glenpike/npm-g_nosudo/blob/master/npm-g-nosudo.sh#L116))

Are you able to tell me whether this was set in the file and what it was set to before you followed the manual instructions?  Wondering if something screwed up here.

**Comment by ucassh** [comment]
Script prints question "Please answer 'y' or 'n'." for about few seconds, and then it's continuing to the end.

I can show You all my enviroment, cause I'm running this under vagrant. In manually_no_sudo.zip You can see config for properly working "no-sudo". In env_4_no_sudo_script.zip You will find a clean config, prepared to run https://github.com/glenpike/npm-g_nosudo in cli (You can see, that I didn't include that automagic command into vagrant script - only for debugging).

This behavior does not tire me, cause manually approach works fine for me :)

https://www.wetransfer.com/downloads/55d0b8167cb6f0d50296732df792aba220151116211904/081e4cdfad6b6275fb5d7f8b140bcc9720151116211904/2d3512

**Comment by glenpike** [comment]
Running the script with the wget command, rather than downloading, changes stdin for the script, so it doesn't work "interactively".  In this case, you have to update your bashrc manually.

I've done a potential workaround for this in a branch on commit 8809586.

Try running the wget command again, but with this URL.

https://raw.githubusercontent.com/glenpike/npm-g_nosudo/workaround-wget-stdin/npm-g-nosudo.sh

**Comment by ucassh** [comment]
Right! when I ran script after simple wget file, everything seems fine-
script is waiting for my decision (in both versions
https://raw.githubusercontent.com/glenpike/npm-g_nosudo/workaround-wget-stdin/npm-g-nosudo.sh
and
https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh).
Unfortunately workaround still doesn't work in
wget -O-
https://raw.githubusercontent.com/glenpike/npm-g_nosudo/workaround-wget-stdin/npm-g-nosudo.sh
| sh

But I can live with that now :)
thanks 4 advice

Pozdrawiam
Łukasz Kaczmarek

2015-11-17 23:20 GMT+01:00 Glen Pike <notifications@github.com>:

**Comment by glenpike** [comment]
With the "workaround piped to shell", it still won't prompt for your input, but it _will_ default to echo-ing the environment settings you need to add to your bashrc, etc.  Here's a snippet from the output on my Vagrant box.

```
Invalid choice

You may need to add the following to your ~/.bashrc / .zshrc file(s)


export NPM_PACKAGES="/home/glenpike/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules${NODE_PATH:+:$NODE_PATH}"
export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"



Done - current package list:
```

If you don't have any objections, I will merge my branch into master with this fix and close this bug.

**Comment by ucassh** [comment]
sure thing
thanks at all :)
