### ISSUE TITLE
npm won't use the new path

### ISSUE THREAD

**Issue by slamidtfyn** [glenpike/npm-g_nosudo#24]
I found this extra command that convinced npm to use the new path for global install:

npm config set prefix '~/.npm-packages'

from https://docs.npmjs.com/getting-started/fixing-npm-permissions

Have tried this on a fresh ubuntu 12.04 install

**Comment by glenpike** [comment]
Hi, can you explain what you mean by the bug report - I'm not sure if this is a bug or not?

My script pretty much does what that page is explaining - it sets the config, but also tries to move any existing global packages to the new location for you. There was an issue with one of the npm commands outlined in #23 which prevented this working, but it may have been fixed now.

**Comment by glenpike** [comment]
Closing this as I don't think it's a bug - script is an alternative to the prefix (tries to help you move existing packages to new prefix automatically)
