### ISSUE TITLE
Line 142: syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by obiwanakin** [glenpike/npm-g_nosudo#6]
When I run the bash file in OS X 10.10, I get this error:
```
bash: line 142: syntax error near unexpected token `)'
bash: line 142: `    [Yy]* ) fix_env;;'
```

**Comment by glenpike** [comment]
Hi, sorry, I've never been able to look at this as I've not run Yosemite.  We have some Yosemite machines at work, so I will endeavour to check the problem.

**Comment by javadoug** [comment]
I saw this problem, too. Instead of calling bash to run the script I called sh.

**Comment by glenpike** [comment]
Closing this issue because could not reproduce on Yosemite- appears that @javadoug's comment may be solution - run with sh not bash.
