### ISSUE TITLE
sh issue when executing through ssh

### ISSUE THREAD

**Issue by clipermark** [glenpike/npm-g_nosudo#8]
I think there's an issue if you want to issue commands through ssh like:

ssh server.com 'grunt -v'

should then return bash: grunt: command not found

I would still recommend option 2 here https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by glenpike** [comment]
Sorry, can you elaborate on that as my script does implement option 2 from that page from what I understand?

Also, are you logging into server.com as the same user who installed the "local" version of npm?

**Comment by clipermark** [comment]
Hi Glen, ignore this ticket. The issue was in my server's profile.
